spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false

server:
  port: 2333

lavalink:
  server:
    password: "YashaLava"
    sources:
      youtube: false

plugins:
  youtube:
    ANDROID:
      playback: false
    TVHTML5EMBEDDED:
      playlistLoading: true
      searching: true
      videoLoading: true
    WEB:
      playback: true
    clients:
    - MUSIC
    - WEB
    - ANDROID
    - ANDROID_TESTSUITE
    - TVHTML5EMBEDDED
    - ANDROID_LITE
    - MEDIA_CONNECT
    - IOS
    remoteCipher:
      url: "https://cipher.kikkia.dev/"
    enabled: true
    oauth:
      enabled: true
      refreshToken: "1//09ifUSRfLt5-8CgYIARAAGAkSNwF-L9Irv9S9udeyywnDhjqDRFZwC6Noc2ggpxmmQvzKb951s-RqPsoGnFPGVQUAZJikj_vfou8"
      skipInitialization: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
  lavasrc:
    sources:
      youtube: true
      yandexmusic: true
      vkmusic: true
    yandexmusic:
      enabled: true
      accessToken: "AQAAAAAWaOQYAAG8Xu4J22kvQEP9qMJ4y9aZk2E"
    vkmusic:
      userToken: "vk1.a.PulXNdyNzAS8F8KR1nkQGo0iyJXOGmIipgmV3UcC9eTICXLBwRXw0qbhV43b9aVITfqB-blu6Z_EKrsmK9AfY4nJFDsKPuk8G1HRvymRyvwt1TrGftNBr5LMstouxfFV5AKeILgIRD_IfY4OnixI9fT3VHmyEwmhUnmEwcAKSJj8w0oPijJbwt0O9RdYhvFNoOi4O1mBfxhlh6Y9GYOb8w"
    youtube:
      countryCode: "RU"
      playlistLoadLimit: 1
      albumLoadLimit: 1
      artistLoadLimit: 1