spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false

server:
  port: 2333

lavalink:
  server:
    password: "YashaLava"
    sources:
      youtube: false

plugins:
  youtube:
    enabled: true
    oauth:
      enabled: true
      oauth2:
        refreshToken: "1//09jhv5UoukuLXCgYIARAAGAkSNwF-L9Irq8gYQ8Mrvd3jaoA8EdYaj3uCOM-w0m7gns7TFOlmSU0fMBUuCnMjFv03ejjhnuH2P5M"
        skipInitialization: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - "ANDROID_MUSIC"
      - "MUSIC"
      - "WEB"
      - "WEBEMBEDDED"
      - "TVHTML5EMBEDDED"
    ANDROID_MUSIC:
      playlistLoading: false
      videoLoading: true
      searching: true
      playback: true
    MUSIC:
      playlistLoading: false
      videoLoading: true
      searching: true
      playback: false
    WEB:
      playlistLoading: false
      videoLoading: true
      searching: true
      playback: true
    WEBEMBEDDED:
      playlistLoading: false
      videoLoading: false
      searching: false
      playback: true
    TVHTML5EMBEDDED:
      playlistLoading: false
      videoLoading: false
      searching: false
      playback: true
  lavasrc:
    sources:
      youtube: true
      yandexmusic: true
      vkmusic: true
    yandexmusic:
      enabled: true
      accessToken: "AQAAAAAWaOQYAAG8Xu4J22kvQEP9qMJ4y9aZk2E"
    vkmusic:
      userToken: "vk1.a.PulXNdyNzAS8F8KR1nkQGo0iyJXOGmIipgmV3UcC9eTICXLBwRXw0qbhV43b9aVITfqB-blu6Z_EKrsmK9AfY4nJFDsKPuk8G1HRvymRyvwt1TrGftNBr5LMstouxfFV5AKeILgIRD_IfY4OnixI9fT3VHmyEwmhUnmEwcAKSJj8w0oPijJbwt0O9RdYhvFNoOi4O1mBfxhlh6Y9GYOb8w"
    youtube:
      countryCode: "RU"
      playlistLoadLimit: 1
      albumLoadLimit: 1
      artistLoadLimit: 1